name: Manual-build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup .NET Core 5.0.102
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102

    - name: Determine semantic version
      uses: dotnet/nbgv@master
      id: nbgv
      with:
        path: dotnet

    - name: Build
      run: dotnet build dotnet/dotnet.sln --configuration Release -p:PackageVersion=${{ steps.nbgv.outputs.SemVer2 }}

    - name: Push NuGet packages to GitHub packages
      run: dotnet nuget push **/*.nupkg
        --source https://nuget.pkg.github.com/CielaNorma/index.json
        --api-key ${{ secrets.SECRET_API_KEY }}
        --no-symbols true
        --skip-duplicate